[package]
name = "github-event"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../rooch/frameworks/move-stdlib" }
MoveosStdlib = { local = "../../rooch/frameworks/moveos-stdlib" }
RoochFramework = { local = "../../rooch/frameworks/rooch-framework" }

[addresses]
github_event = "0x726b3e4cdbcd2e0cd0d5916bc3f8ce0970760e3d048b5ab0e84766c68a72fb9b"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
