[package]
name = "github-event"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../../rooch/frameworks/move-stdlib" }
MoveosStdlib = { local = "../../../rooch/frameworks/moveos-stdlib" }
RoochFramework = { local = "../../../rooch/frameworks/rooch-framework" }

[addresses]
github_event = "0x28aae6ffa6ec731f1c5bab813e65f236e8700980d031e1f2bbaaa54285421ed3"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
